# Generated by Django 4.2 on 2023-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treballador',
            name='mes_vacances',
        ),
        migrations.AddField(
            model_name='mesvacances',
            name='treballadors',
            field=models.ManyToManyField(to='brigada.treballador'),
        ),
    ]
